import { describe, expect, it } from 'vitest';

import type { Workflow } from '../schema/index.js';

import { generate } from './generate.js';

describe('generate — fixture snapshots', () => {
  it('minimal workflow', () => {
    const wf: Workflow = {
      name: 'CI',
      on: { push: { branches: ['main'] } },
      jobs: {
        build: {
          'runs-on': 'ubuntu-latest',
          steps: [{ uses: 'actions/checkout@v4' }],
        },
      },
    };
    expect(generate(wf)).toMatchInlineSnapshot(`
      "name: CI
      on:
        push:
          branches:
            - main
      jobs:
        build:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v4
      "
    `);
  });

  it('expression in env stays unquoted', () => {
    const wf: Workflow = {
      name: 'Deploy',
      on: { push: { branches: ['main'] } },
      jobs: {
        deploy: {
          'runs-on': 'ubuntu-latest',
          env: { TOKEN: '${{ secrets.DEPLOY_TOKEN }}' },
          steps: [{ uses: 'actions/checkout@v4' }],
        },
      },
    };
    expect(generate(wf)).toMatchInlineSnapshot(`
      "name: Deploy
      on:
        push:
          branches:
            - main
      jobs:
        deploy:
          runs-on: ubuntu-latest
          env:
            TOKEN: \${{ secrets.DEPLOY_TOKEN }}
          steps:
            - uses: actions/checkout@v4
      "
    `);
  });

  it('multi-line run uses block literal', () => {
    const wf: Workflow = {
      name: 'Test',
      on: { pull_request: {} },
      jobs: {
        test: {
          'runs-on': 'ubuntu-latest',
          steps: [{ uses: 'actions/checkout@v4' }, { run: 'npm ci\nnpm test\nnpm run build' }],
        },
      },
    };
    expect(generate(wf)).toMatchInlineSnapshot(`
      "name: Test
      on:
        pull_request: {}
      jobs:
        test:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v4
            - run: |-
                npm ci
                npm test
                npm run build
      "
    `);
  });

  it('matrix strategy', () => {
    const wf: Workflow = {
      name: 'Matrix',
      on: { push: {} },
      jobs: {
        test: {
          'runs-on': 'ubuntu-latest',
          strategy: {
            matrix: {
              'node-version': [18, 20, 22],
              os: ['ubuntu-latest', 'macos-latest'],
            },
          },
          steps: [{ uses: 'actions/checkout@v4' }],
        },
      },
    };
    expect(generate(wf)).toMatchInlineSnapshot(`
      "name: Matrix
      on:
        push: {}
      jobs:
        test:
          runs-on: ubuntu-latest
          strategy:
            matrix:
              node-version:
                - 18
                - 20
                - 22
              os:
                - ubuntu-latest
                - macos-latest
          steps:
            - uses: actions/checkout@v4
      "
    `);
  });

  it('reusable workflow call', () => {
    const wf: Workflow = {
      name: 'Caller',
      on: { push: {} },
      jobs: {
        deploy: {
          uses: './.github/workflows/reusable-deploy.yml',
          with: { environment: 'production' },
          secrets: 'inherit',
        },
      },
    };
    expect(generate(wf)).toMatchInlineSnapshot(`
      "name: Caller
      on:
        push: {}
      jobs:
        deploy:
          uses: ./.github/workflows/reusable-deploy.yml
          with:
            environment: production
          secrets: inherit
      "
    `);
  });
});

describe('generate — options', () => {
  it('prepends the header as YAML comments', () => {
    const wf: Workflow = {
      on: { push: {} },
      jobs: {
        build: {
          'runs-on': 'ubuntu-latest',
          steps: [{ run: 'echo hi' }],
        },
      },
    };
    const out = generate(wf, { header: 'generated by arc-workflows\ndo not edit' });
    expect(out.startsWith('# generated by arc-workflows\n# do not edit\n')).toBe(true);
  });
});
